name: Add Label on PR
on:
  pull_request:
    branches: [ develop, main ]
    types: [ opened, synchronize, reopened ]

jobs:
  label-sync:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: GitHub Labeler Action
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
